---
- hosts: local

  tasks:
    - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
      cron:
        name: "echo hi"
        minute: "20"
        job: "/bin/echo hi"

